In [1]:
import pandas as pd
import numpy as np

**Loading Dataset**

In [2]:
s=pd.read_csv(r'C:\Users\CVR\Downloads\Automobile.csv')

**Display Dataset**

In [3]:
s

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [4]:
s.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [5]:
s.tail()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
s.describe()

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,125.189055,98.797015,174.200995,65.889055,53.766667,2555.666667,126.875622,3.329701,3.261741,10.164279,103.263682,5121.393035,25.179104,30.686567,13207.129353
std,1.254802,33.572966,6.066366,12.322175,2.101471,2.447822,517.296727,41.546834,0.268166,0.317875,4.004965,37.389372,479.624905,6.423220,6.815150,7947.066342
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,101.000000,94.500000,166.800000,64.100000,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,122.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,150.000000,102.400000,183.500000,66.600000,55.500000,2926.000000,141.000000,3.580000,3.460000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,120.900000,208.100000,72.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000

In [7]:
s.info

<bound method DataFrame.info of      symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std
1            3                168  alfa-romero       gas        std
2            1                168  alfa-romero       gas        std
3            2                164         audi       gas        std
4            2                164         audi       gas        std
..         ...                ...          ...       ...        ...
196         -1                 95        volvo       gas        std
197         -1                 95        volvo       gas      turbo
198         -1                 95        volvo       gas        std
199         -1                 95        volvo    diesel      turbo
200         -1                 95        volvo       gas      turbo

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        88.6
1               two  convertible          rwd           front        88.6
2               two    hatchback          rwd           front        94.5
3              four        sedan          fwd           front        99.8
4              four        sedan          4wd           front        99.4
..              ...          ...          ...             ...         ...
196            four        sedan          rwd           front       109.1
197            four        sedan          rwd           front       109.1
198            four        sedan          rwd           front       109.1
199            four        sedan          rwd           front       109.1
200            four        sedan          rwd           front       109.1

     ...  engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0    ...          130         mpfi  3.47    2.68               9.0        111
1    ...          130         mpfi  3.47    2.68               9.0        111
2    ...          152         mpfi  2.68    3.47               9.0        154
3    ...          109         mpfi  3.19    3.40              10.0        102
4    ...          136         mpfi  3.19    3.40               8.0        115
..   ...          ...          ...   ...     ...               ...        ...
196  ...          141         mpfi  3.78    3.15               9.5        114
197  ...          141         mpfi  3.78    3.15               8.7        160
198  ...          173         mpfi  3.58    2.87               8.8        134
199  ...          145          idi  3.01    3.40              23.0        106
200  ...          141         mpfi  3.78    3.15               9.5        114

     peak_rpm city_mpg  highway_mpg  price
0        5000       21           27  13495
1        5000       21           27  16500
2        5000       19           26  16500
3        5500       24           30  13950
4        5500       18           22  17450
..        ...      ...          ...    ...
196      5400       23           28  16845
197      5300       19           25  19045
198      5500       18           23  21485
199      4800       26           27  22470
200      5400       19           25  22625

[201 rows x 26 columns]>

# Handling Missing Values

**Display Missing Values**

In [8]:
missing_values = s.isnull().sum()

In [9]:
missing_values

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [10]:
missing_value = s.isna().sum()

In [11]:
missing_value

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

**Replacing Column data with**

**1.Mean/Median for horsepower, price.** 

**2.Mode for categorical columns (number_of_doors, fuel_type).**

In [12]:
s['horsepower'].fillna(s['horsepower'].median(),inplace=True)
s['price'].fillna(s['price'].median(), inplace=True)
s['number_of_doors'].fillna(s['number_of_doors'].mode()[0], inplace=True)
s['fuel_type'].fillna(s['fuel_type'].mode()[0], inplace=True)

In [13]:
s

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# String & Categorical Data Preprocessing

In [14]:
s.dtypes

symboling                int64
normalized_losses        int64
make                    object
fuel_type               object
aspiration              object
number_of_doors         object
body_style              object
drive_wheels            object
engine_location         object
wheel_base             float64
length                 float64
width                  float64
height                 float64
curb_weight              int64
engine_type             object
number_of_cylinders     object
engine_size              int64
fuel_system             object
bore                   float64
stroke                 float64
compression_ratio      float64
horsepower               int64
peak_rpm                 int64
city_mpg                 int64
highway_mpg              int64
price                    int64
dtype: object

**Convert categorical data into lowercase and remove special characters (make, 
fuel_type, aspiration, etc.).**

In [15]:
columns_to_clean = ['make', 'fuel_type', 'aspiration', 'number_of_doors', 'body_style', 
                    'drive_wheels', 'engine_location', 'engine_type', 'number_of_cylinders', 
                    'fuel_system']
for column in columns_to_clean:
    s[column] = s[column].str.lower().str.replace(r'[^a-z0-9\s]', '', regex=True)

In [16]:
s

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfaromero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfaromero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfaromero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Standardize number_of_cylinders: 
Convert words ("four", "six", "eight") to integers (4, 6, 8).**

In [17]:
s['number_of_cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [18]:
cylinder_map = {
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'eight': 8,
    'twelve': 12
}

s['number_of_cylinders'] = s['number_of_cylinders'].replace(cylinder_map)
s['number_of_cylinders'].head()

0    4
1    4
2    6
3    4
4    5
Name: number_of_cylinders, dtype: int64

**Replace "?" or NaN values with appropriate replacements.**

In [19]:
s.replace('?', np.nan, inplace=True)
numerical_cols = s.select_dtypes(include=['float64', 'int64']).columns
s[numerical_cols] = s[numerical_cols].fillna(s[numerical_cols].median())


categorical_cols = s.select_dtypes(include=['object']).columns
for col in categorical_cols:
    s[col].fillna(s[col].mode()[0], inplace=True)

print(s.head())

   symboling  normalized_losses        make fuel_type aspiration  \
0          3                168  alfaromero       gas        std
1          3                168  alfaromero       gas        std
2          1                168  alfaromero       gas        std
3          2                164        audi       gas        std
4          2                164        audi       gas        std

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...
1             two  convertible          rwd           front        88.6  ...
2             two    hatchback          rwd           front        94.5  ...
3            four        sedan          fwd           front        99.8  ...
4            four        sedan          4wd           front        99.4  ...

   engine_size  fuel_system  bore  stroke compression_ratio  horsepower  \
0          130         mpfi  3.47    2.68               9.0         111
1          130         mpfi  3.47    2.68               9.0         111
2          152         mpfi  2.68    3.47               9.0         154
3          109         mpfi  3.19    3.40              10.0         102
4          136         mpfi  3.19    3.40               8.0         115

   peak_rpm city_mpg  highway_mpg  price
0      5000       21           27  13495
1      5000       21           27  16500
2      5000       19           26  16500
3      5500       24           30  13950
4      5500       18           22  17450

[5 rows x 26 columns]

In [20]:
s['number_of_cylinders']

0      4
1      4
2      6
3      4
4      5
      ..
196    4
197    4
198    6
199    6
200    4
Name: number_of_cylinders, Length: 201, dtype: int64

**Standardize fuel_system categories (e.g., mpfi, spdi → Multi-Point Fuel Injection, 
Single-Point Fuel Injection).**

In [21]:
s['fuel_system'].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [22]:
fuel_system_map = {
    'mpfi': 'Multi-Point Fuel Injection',
    'mfi': 'Multi-Point Fuel Injection',
    'spfi': 'Single-Point Fuel Injection',
    'spdi': 'Single-Point Fuel Injection',
    '2bbl': 'Two-Barrel Carburetor',
    '4bbl': 'Four-Barrel Carburetor',
    'idi': 'Indirect Fuel Injection',
    '1bbl': 'One-Barrel Carburetor'
}

# Standardize the 'fuel_system' column using the mapping dictionary
s['fuel_system'] = s['fuel_system'].replace(fuel_system_map)

# Check the updated DataFrame
print(s['fuel_system'].unique())

['Multi-Point Fuel Injection' 'Two-Barrel Carburetor'
 'One-Barrel Carburetor' 'Single-Point Fuel Injection'
 'Four-Barrel Carburetor' 'Indirect Fuel Injection']

# Numeric Feature Processing

**Convert "horsepower" and "peak_rpm" to integers (handle missing values first).**

In [23]:
s['horsepower'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
196    False
197    False
198    False
199    False
200    False
Name: horsepower, Length: 201, dtype: bool

In [24]:
s['peak_rpm'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
196    False
197    False
198    False
199    False
200    False
Name: peak_rpm, Length: 201, dtype: bool

In [25]:
s['horsepower']=s['horsepower'].astype(np.int16)

In [26]:
s['horsepower'].dtype

dtype('int16')

In [27]:
s['peak_rpm']=s['peak_rpm'].astype(np.int16)

In [28]:
s['peak_rpm'].dtype

dtype('int16')

**Convert price to numeric and fill missing values.**

In [29]:
s['price'].dtype

dtype('int64')

In [30]:
s['price'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
196    False
197    False
198    False
199    False
200    False
Name: price, Length: 201, dtype: bool

In [31]:
s.isnull().sum()

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [32]:
s.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfaromero,gas,std,two,convertible,rwd,front,88.6,...,130,Multi-Point Fuel Injection,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfaromero,gas,std,two,convertible,rwd,front,88.6,...,130,Multi-Point Fuel Injection,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfaromero,gas,std,two,hatchback,rwd,front,94.5,...,152,Multi-Point Fuel Injection,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,Multi-Point Fuel Injection,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,Multi-Point Fuel Injection,3.19,3.40,8.0,115,5500,18,22,17450

In [33]:
s.dtypes

symboling                int64
normalized_losses        int64
make                    object
fuel_type               object
aspiration              object
number_of_doors         object
body_style              object
drive_wheels            object
engine_location         object
wheel_base             float64
length                 float64
width                  float64
height                 float64
curb_weight              int64
engine_type             object
number_of_cylinders      int64
engine_size              int64
fuel_system             object
bore                   float64
stroke                 float64
compression_ratio      float64
horsepower               int16
peak_rpm                 int16
city_mpg                 int64
highway_mpg              int64
price                    int64
dtype: object

In [34]:
s.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [35]:
s['horsepower']

0      111
1      111
2      154
3      102
4      115
      ...
196    114
197    160
198    134
199    106
200    114
Name: horsepower, Length: 201, dtype: int16

In [36]:
s['horsepower']=s['horsepower']*0.7457
s['horsepower'].head()

0     82.7727
1     82.7727
2    114.8378
3     76.0614
4     85.7555
Name: horsepower, dtype: float64

In [37]:
columns = ['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
           'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
           'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
           'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
           'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
           'highway_mpg', 'price']
for col in s.columns:
    print(f"Unique values in '{col}':")
    print(s[col].unique())
    print('-' * 50)

Unique values in 'symboling':
[ 3  1  2  0 -1 -2]
--------------------------------------------------
Unique values in 'normalized_losses':
[168 164 161 158 192 188 149 121  98  81 118 148 110 145 137 101  78 106
  85 107 115 104 113 150 129 119 105  93 122 142 140 153 139 125 128 103
 108 194 231 154  74 141 186  83 102  89  87  77  91 134  65 197  90 133
  94 256 132  95]
--------------------------------------------------
Unique values in 'make':
['alfaromero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedesbenz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']
--------------------------------------------------
Unique values in 'fuel_type':
['gas' 'diesel']
--------------------------------------------------
Unique values in 'aspiration':
['std' 'turbo']
--------------------------------------------------
Unique values in 'number_of_doors':
['two' 'four']
--------------------------------------------------
Unique values in 'body_style':
['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
--------------------------------------------------
Unique values in 'drive_wheels':
['rwd' 'fwd' '4wd']
--------------------------------------------------
Unique values in 'engine_location':
['front' 'rear']
--------------------------------------------------
Unique values in 'wheel_base':
[ 88.6  94.5  99.8  99.4 105.8 101.2 103.5 110.   88.4  93.7 103.3  95.9
  86.6  96.5  94.3  96.  113.  102.   93.1  95.3  98.8 104.9 106.7 115.6
  96.6 120.9 112.  102.7  93.   96.3  95.1  97.2 100.4  91.3  99.2 107.9
 114.2 108.   89.5  96.1  99.1  93.3  97.   96.9  95.7  98.4 102.4 102.9
 104.5  97.3 104.3 109.1]
--------------------------------------------------
Unique values in 'length':
[168.8 171.2 176.6 177.3 192.7 176.8 189.  193.8 197.  141.1 155.9 158.8
 157.3 174.6 173.2 144.6 150.  163.4 157.1 167.5 175.4 169.1 170.7 172.6
 199.6 191.7 159.1 166.8 169.  177.8 175.  190.9 187.5 202.6 180.3 208.1
 199.2 178.4 173.  172.4 165.3 170.2 165.6 162.4 173.4 181.7 184.6 178.5
 186.7 198.9 167.3 168.9 181.5 186.6 156.9 157.9 172.  173.5 173.6 158.7
 169.7 166.3 168.7 176.2 175.6 183.5 187.8 171.7 159.3 165.7 180.2 183.1
 188.8]
--------------------------------------------------
Unique values in 'width':
[64.1 65.5 66.2 66.4 66.3 71.4 64.8 66.9 67.9 70.9 60.3 63.6 63.8 64.6
 63.9 64.  65.2 62.5 66.  61.8 69.6 70.6 64.2 65.7 66.5 66.1 70.3 71.7
 70.5 72.  68.  64.4 65.4 68.4 68.3 65.  66.6 63.4 65.6 67.7 67.2 68.9
 68.8]
--------------------------------------------------
Unique values in 'height':
[48.8 52.4 54.3 53.1 55.7 55.9 53.7 56.3 53.2 52.  50.8 50.6 59.8 50.2
 52.6 54.5 58.3 53.3 54.1 51.  53.5 51.4 52.8 47.8 49.6 55.5 54.4 56.5
 58.7 54.9 56.7 55.4 54.8 49.4 51.6 54.7 55.1 56.1 49.7 56.  55.2 50.5
 52.5 53.  59.1 53.9 55.6 56.2 57.5]
--------------------------------------------------
Unique values in 'curb_weight':
[2548 2823 2337 2824 2507 2844 2954 3086 2395 2710 2765 3055 3230 3380
 3505 1488 1874 1909 1876 2128 1967 1989 2191 2535 2811 1713 1819 1837
 1940 1956 2010 2024 2236 2289 2304 2372 2465 2293 2734 4066 3950 1890
 1900 1905 1945 1950 2380 2385 2500 2410 2443 2425 2670 2700 3515 3750
 3495 3770 3740 3685 3900 3715 2910 1918 1944 2004 2145 2370 2328 2833
 2921 2926 2365 2405 2403 1889 2017 1938 1951 2028 1971 2037 2008 2324
 2302 3095 3296 3060 3071 3139 3020 3197 3430 3075 3252 3285 3485 3130
 2818 2778 2756 2800 2579 2460 2658 2695 2707 2758 2808 2847 2050 2120
 2240 2190 2340 2510 2290 2455 2420 2650 1985 2040 2015 2280 3110 2081
 2109 2275 2094 2122 2140 2169 2204 2265 2300 2540 2536 2551 2679 2714
 2975 2326 2480 2414 2458 2976 3016 3131 3151 2261 2209 2264 2212 2319
 2254 2221 2661 2563 2912 3034 2935 3042 3045 3157 2952 3049 3012 3217
 3062]
--------------------------------------------------
Unique values in 'engine_type':
['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf']
--------------------------------------------------
Unique values in 'number_of_cylinders':
[ 4  6  5  3 12  2  8]
--------------------------------------------------
Unique values in 'engine_size':
[130 152 109 136 131 108 164 209  61  90  98 122 156  92  79 110 111 119
 258 326  91  70  80 140 134 183 234 308 304  97 103 120 181 151 194 132
 121 146 171 161 141 173 145]
--------------------------------------------------
Unique values in 'fuel_system':
['Multi-Point Fuel Injection' 'Two-Barrel Carburetor'
 'One-Barrel Carburetor' 'Single-Point Fuel Injection'
 'Four-Barrel Carburetor' 'Indirect Fuel Injection']
--------------------------------------------------
Unique values in 'bore':
[3.47 2.68 3.19 3.13 3.5  3.31 3.62 2.91 3.03 2.97 3.34 3.6  2.92 3.15
 3.43 3.63 3.54 3.08 3.28 3.39 3.76 3.58 3.46 3.8  3.78 3.17 3.35 3.59
 2.99 3.33 3.7  3.61 3.94 3.74 2.54 3.05 3.27 3.24 3.01]
--------------------------------------------------
Unique values in 'stroke':
[2.68 3.47 3.4  2.8  3.19 3.39 3.03 3.11 3.23 3.46 3.9  3.41 3.07 3.58
 4.17 2.76 3.15 3.5  3.16 3.64 3.1  3.35 3.12 3.86 3.29 3.27 3.52 2.19
 3.21 2.9  2.07 2.36 2.64 3.08 3.54 2.87]
--------------------------------------------------
Unique values in 'compression_ratio':
[ 9.   10.    8.    8.5   8.3   8.8   9.5   9.6   9.41  9.4   7.6   7.
  9.2  10.1   9.1   8.1  11.5   8.6  22.7  22.   21.5   7.5  21.9   7.8
  8.4  21.    8.7   9.31  9.3   7.7  22.5  23.  ]
--------------------------------------------------
Unique values in 'horsepower':
[ 82.7727 114.8378  76.0614  85.7555  82.027  104.398   75.3157  90.2297
 135.7174  35.7936  52.199   50.7076  65.6216 108.1265  43.2506  56.6732
  44.742   64.1302  74.57    58.1646  67.113  131.2432 195.3734 100.6695
  62.6388  47.7248  89.484   53.6904  91.7211 115.5835 137.2088 130.4975
  86.5012  51.4533  41.0135  72.3329 113.3464 119.312  149.14    70.8415
 105.8894 106.6351 154.3599  54.4361  61.1474  70.0958  46.2334  41.7592
  83.5184  68.6044 120.0577 116.3292  38.7764  63.3845  85.0098 120.8034
  99.9238  79.0442]
--------------------------------------------------
Unique values in 'peak_rpm':
[5000 5500 5800 4250 5400 5100 4800 6000 4750 4650 4200 4350 4500 5200
 4150 5600 5900 5250 4900 4400 6600 5300]
--------------------------------------------------
Unique values in 'city_mpg':
[21 19 24 18 17 23 20 16 15 47 38 37 31 49 30 27 25 13 26 36 22 14 45 28
 32 35 34 29 33]
--------------------------------------------------
Unique values in 'highway_mpg':
[27 26 30 22 25 20 29 28 53 43 41 38 24 54 42 34 33 31 19 17 23 32 39 18
 16 37 50 36 47 46]
--------------------------------------------------
Unique values in 'price':
[13495 16500 13950 17450 15250 17710 18920 23875 16430 16925 20970 21105
 24565 30760 41315 36880  5151  6295  6575  5572  6377  7957  6229  6692
  7609  8558  8921 12964  6479  6855  5399  6529  7129  7295  7895  9095
  8845 10295 12945 10345  6785 11048 32250 35550 36000  5195  6095  6795
  6695  7395 10945 11845 13645 15645  8495 10595 10245 10795 11245 18280
 18344 25552 28248 28176 31600 34184 35056 40960 45400 16503  5389  6189
  6669  7689  9959  8499 12629 14869 14489  6989  8189  9279  5499  7099
  6649  6849  7349  7299  7799  7499  7999  8249  8949  9549 13499 14399
 17199 19699 18399 11900 13200 12440 13860 15580 16900 16695 17075 16630
 17950 18150 12764 22018 32528 34028 37028  9295  9895 11850 12170 15040
 15510 18620  5118  7053  7603  7126  7775  9960  9233 11259  7463 10198
  8013 11694  5348  6338  6488  6918  7898  8778  6938  7198  7788  7738
  8358  9258  8058  8238  9298  9538  8449  9639  9989 11199 11549 17669
  8948 10698  9988 10898 11248 16558 15998 15690 15750  7975  7995  8195
  9495  9995 11595  9980 13295 13845 12290 12940 13415 15985 16515 18420
 18950 16845 19045 21485 22470 22625]
--------------------------------------------------

# Feature Engineering on Numeric Columns

**Create New Features:** 

**Power-to-weight ratio = horsepower / curb_weight.** 

**Engine efficiency = horsepower / engine_size.**

**Fuel efficiency = city_mpg / highway_mpg.**

In [38]:
s['power-to-weight']=s['horsepower']/s['curb_weight']

In [39]:
s['power-to-weight']

0      0.032485
1      0.032485
2      0.040679
3      0.032547
4      0.030367
         ...
196    0.028797
197    0.039132
198    0.033175
199    0.024571
200    0.027763
Name: power-to-weight, Length: 201, dtype: float64

In [40]:
s['Engine efficiency']=s['horsepower']/ s['engine_size']

In [41]:
s['Engine efficiency']

0      0.636713
1      0.636713
2      0.755512
3      0.697811
4      0.630555
         ...
196    0.602906
197    0.846184
198    0.577594
199    0.545132
200    0.602906
Name: Engine efficiency, Length: 201, dtype: float64

In [42]:
s['Fuel efficiency'] = s['city_mpg'] / s['highway_mpg']

In [43]:
s['Fuel efficiency']

0      0.777778
1      0.777778
2      0.730769
3      0.800000
4      0.818182
         ...
196    0.821429
197    0.760000
198    0.782609
199    0.962963
200    0.760000
Name: Fuel efficiency, Length: 201, dtype: float64

In [44]:
s['compression_ratio']

0       9.0
1       9.0
2       9.0
3      10.0
4       8.0
       ...
196     9.5
197     8.7
198     8.8
199    23.0
200     9.5
Name: compression_ratio, Length: 201, dtype: float64

In [47]:
compression_categories=[]
for value in s['compression_ratio']:
    if value<9:
        compression_categories.append('Low')
    elif 9<= value <=11:
        compression_categories.append('Medium')
    else:
        compression_categories.append('High')
s['compression_ratio']=compression_categories
s['compression_ratio']

0      Medium
1      Medium
2      Medium
3      Medium
4         Low
        ...
196    Medium
197       Low
198       Low
199      High
200    Medium
Name: compression_ratio, Length: 201, dtype: object

# Handling Date or Range Values

**Extract ranges from normalized_losses and create bins (e.g., Low, Medium, High 
loss categories).**

In [49]:
s['normalized_losses'].unique()

array([168, 164, 161, 158, 192, 188, 149, 121,  98,  81, 118, 148, 110,
       145, 137, 101,  78, 106,  85, 107, 115, 104, 113, 150, 129, 119,
       105,  93, 122, 142, 140, 153, 139, 125, 128, 103, 108, 194, 231,
       154,  74, 141, 186,  83, 102,  89,  87,  77,  91, 134,  65, 197,
        90, 133,  94, 256, 132,  95], dtype=int64)

In [53]:
ranges_nl=[]
for value in s['normalized_losses']:
    if 95 <= value >=120:
        ranges_nl.append('Low Loss')
    elif 121 <= value >=145:
        ranges_nl.append('Medium Loss')
    else:
        ranges_nl.append('HighLoss')
               
s['normalized_losses']=ranges_nl
s['normalized_losses']

0      Low Loss
1      Low Loss
2      Low Loss
3      Low Loss
4      Low Loss
         ...
196    HighLoss
197    HighLoss
198    HighLoss
199    HighLoss
200    HighLoss
Name: normalized_losses, Length: 201, dtype: object

# Encoding Categorical Features

**Label Encoding for fuel_type, aspiration, drive_wheels, etc.**

In [55]:
from sklearn.preprocessing import LabelEncoder

In [57]:
categorical_columns = ['fuel_type', 'aspiration', 'drive_wheels']

label_encoder = LabelEncoder()
for column in categorical_columns:
    s[column] = label_encoder.fit_transform(s[column])

print(s.head())

   symboling normalized_losses  make  fuel_type  aspiration number_of_doors  \
0          3          Low Loss     0          1           0             two
1          3          Low Loss     0          1           0             two
2          1          Low Loss     0          1           0             two
3          2          Low Loss     1          1           0            four
4          2          Low Loss     1          1           0            four

   body_style  drive_wheels  engine_location  wheel_base  ...  stroke  \
0           0             2                0        88.6  ...    2.68
1           0             2                0        88.6  ...    2.68
2           2             2                0        94.5  ...    3.47
3           3             1                0        99.8  ...    3.40
4           3             0                0        99.4  ...    3.40

   compression_ratio  horsepower  peak_rpm  city_mpg  highway_mpg  price  \
0             Medium     82.7727      5000        21           27  13495
1             Medium     82.7727      5000        21           27  16500
2             Medium    114.8378      5000        19           26  16500
3             Medium     76.0614      5500        24           30  13950
4                Low     85.7555      5500        18           22  17450

   power-to-weight  Engine efficiency  Fuel efficiency
0         0.032485           0.636713         0.777778
1         0.032485           0.636713         0.777778
2         0.040679           0.755512         0.730769
3         0.032547           0.697811         0.800000
4         0.030367           0.630555         0.818182

[5 rows x 29 columns]

**One-Hot Encoding for body_style, engine_type, and fuel_system.**

In [58]:
s_encoded = pd.get_dummies(s, columns=['body_style', 'engine_type', 'fuel_system'], drop_first=True)
print(s_encoded.head())

   symboling normalized_losses  make  fuel_type  aspiration number_of_doors  \
0          3          Low Loss     0          1           0             two
1          3          Low Loss     0          1           0             two
2          1          Low Loss     0          1           0             two
3          2          Low Loss     1          1           0            four
4          2          Low Loss     1          1           0            four

   drive_wheels  engine_location  wheel_base  length  ...  engine_type_1  \
0             2                0        88.6   168.8  ...          False
1             2                0        88.6   168.8  ...          False
2             2                0        94.5   171.2  ...          False
3             1                0        99.8   176.6  ...          False
4             0                0        99.4   176.6  ...          False

   engine_type_2  engine_type_3  engine_type_4  engine_type_5  fuel_system_1  \
0          False          False          False          False          False
1          False          False          False          False          False
2          False          False           True          False          False
3           True          False          False          False          False
4           True          False          False          False          False

   fuel_system_2 fuel_system_3  fuel_system_4  fuel_system_5
0           True         False          False          False
1           True         False          False          False
2           True         False          False          False
3           True         False          False          False
4           True         False          False          False

[5 rows x 40 columns]

# Data Scaling & Normalization

**Scale numerical features (length, width, height, curb_weight, engine_size) 
using Min-Max Scaling or Standardization.**

In [59]:
from sklearn.preprocessing import MinMaxScaler
numerical_cols = ['length', 'width', 'height', 'curb_weight', 'engine_size']
scaler = MinMaxScaler()
s[numerical_cols] = scaler.fit_transform(s[numerical_cols])
print(s.head())

   symboling normalized_losses  make  fuel_type  aspiration number_of_doors  \
0          3          Low Loss     0          1           0             two
1          3          Low Loss     0          1           0             two
2          1          Low Loss     0          1           0             two
3          2          Low Loss     1          1           0            four
4          2          Low Loss     1          1           0            four

   body_style  drive_wheels  engine_location  wheel_base  ...  stroke  \
0           0             2                0        88.6  ...    2.68
1           0             2                0        88.6  ...    2.68
2           2             2                0        94.5  ...    3.47
3           3             1                0        99.8  ...    3.40
4           3             0                0        99.4  ...    3.40

   compression_ratio  horsepower  peak_rpm  city_mpg  highway_mpg  price  \
0             Medium     82.7727      5000        21           27  13495
1             Medium     82.7727      5000        21           27  16500
2             Medium    114.8378      5000        19           26  16500
3             Medium     76.0614      5500        24           30  13950
4                Low     85.7555      5500        18           22  17450

   power-to-weight  Engine efficiency  Fuel efficiency
0         0.032485           0.636713         0.777778
1         0.032485           0.636713         0.777778
2         0.040679           0.755512         0.730769
3         0.032547           0.697811         0.800000
4         0.030367           0.630555         0.818182

[5 rows x 29 columns]

In [60]:
from sklearn.preprocessing import StandardScaler
numerical_cols = ['length', 'width', 'height', 'curb_weight', 'engine_size']
scaler = StandardScaler()
s[numerical_cols] = scaler.fit_transform(s[numerical_cols])
print(s.head())

   symboling normalized_losses  make  fuel_type  aspiration number_of_doors  \
0          3          Low Loss     0          1           0             two
1          3          Low Loss     0          1           0             two
2          1          Low Loss     0          1           0             two
3          2          Low Loss     1          1           0            four
4          2          Low Loss     1          1           0            four

   body_style  drive_wheels  engine_location  wheel_base  ...  stroke  \
0           0             2                0        88.6  ...    2.68
1           0             2                0        88.6  ...    2.68
2           2             2                0        94.5  ...    3.47
3           3             1                0        99.8  ...    3.40
4           3             0                0        99.4  ...    3.40

   compression_ratio  horsepower  peak_rpm  city_mpg  highway_mpg  price  \
0             Medium     82.7727      5000        21           27  13495
1             Medium     82.7727      5000        21           27  16500
2             Medium    114.8378      5000        19           26  16500
3             Medium     76.0614      5500        24           30  13950
4                Low     85.7555      5500        18           22  17450

   power-to-weight  Engine efficiency  Fuel efficiency
0         0.032485           0.636713         0.777778
1         0.032485           0.636713         0.777778
2         0.040679           0.755512         0.730769
3         0.032547           0.697811         0.800000
4         0.030367           0.630555         0.818182

[5 rows x 29 columns]

In [62]:
s.shape

(201, 29)